version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.11.10
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Plan
          command: terraform plan
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve
  test:
    docker:
    - image: circleci/ruby:2.4-node-browsers
    working_directory: ~/awsspec/
    steps:
      - checkout
      - run:
          name: Get Dir
          command: ls
      - run:
          name: Bundle install
          command: bundle install --path vendor/bundle
      - run:
          name: Test
          command: bundle exec rake spec
  destroy:
    docker:
      - image: hashicorp/terraform:0.11.10
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Destroy
          command: terraform destroy -auto-approve
workflows:
  version: 2
  build-test-and-destroy:
    jobs:
      - build
      - test:
          requires:
            - build
      - destroy:
          requires:
            - build
            - test
