version: 2

defaults: &terraform
  working_directory: ~/project
  docker:
    - image: hashicorp/terraform:0.11.10

ruby: &ruby
  working_directory: ~/project
  docker:
    - image: circleci/ruby:2.4-node-browsers


jobs:
  build:
    <<: *terraform
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Plan
          command: terraform plan
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve
  test:
    <<: *terraform
    working_directory: ~/project/awsspec/
    steps:
      - checkout
      - run:
          name: Get Dir
          command: ls
      - run:
          name: Install Bundler
          command: gem install bundler
      - run:
          name: Bundle install
          command: bundle install --path vendor/bundle
      - run:
          name: Test
          command: bundle exec rake spec
  destroy:
    <<: *terraform
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Destroy
          command: terraform destroy -auto-approve
workflows:
  version: 2
  build-test-and-destroy:
    jobs:
      - build
      - test:
          requires:
            - build
      - destroy:
          requires:
            - build
            - test
